### PR TITLE
Add Turkish Translations --> lbi-gui.pro

### PR DESCRIPTION
**Pull request by MertGunduz**
Hello Marcel,

I am started to working on the translations.

Can you check if there are any problems with the file, thanks!

Let me know :-)

### CODE REVIEW

**Comment by mrclksr** [comment]
Hi Mehmet,

excellent. The .ts file looks good, as far as I can tell :-). What's missing is the addition of `locale/lbi-gui_tr.ts` to the white space separated list `TRANSLATIONS` in `lbi-gui.pro`. Please note that I made lbi-gui a sub module (https://github.com/nomadbsd/lbi-gui). I can apply your changes manually there for now, so that's not a problem.

**Comment by MertGunduz** [comment]
Hello Marcel,

Thanks for the information and quick response! :-)

```
SOURCES		= lbi-gui
TRANSLATIONS	= locale/lbi-gui_de.ts \
                  locale/lbi-gui_tr.ts
```
Should it be like this?

**Comment by mrclksr** [comment]
Perfect!

**Comment by MertGunduz** [comment]
Thanks! Added :-)

**Comment by mrclksr** [comment]
Thank you :-)

**Pull request merged**
